---
# tasks file for user9.nginx


tasks:
  - name: "Check if EPEL repo is already configured"
    stat: path={{ epel_repofile_path }}
    register: epel_repofile_result
    when: ansible_os_family == "EL"
 
  - name: "Install EPEL repo"
    yum:
      name: "{{ epel_repo_url }}"
      state: present
    register: result
    when: 
      - not epel_repofile_result.stat.exists
      - ansible_os_family == "EL"
 
  - name: "Import EPEL GPG key"
    rpm_key:
      key: "{{ epel_repo_gpg_key_url }}"
      state: present
    when: 
      - not epel_repofile_result.stat.exists
      - ansible_os_family == "EL"
  
  - name: "Install nginx"
    package:
      name: nginx
      state: present


