---
# tasks file for user9.nginx
 
  
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: no
  when: 
    - ansible_os_family == "RedHat"

- name: Update repositories cache for deb
  apt:
    update_cache: yes
  when: 
    - ansible_os_family == "Debian"

- name: "Install nginx"
  package:
    name: nginx
    state: present

- lineinfile:
    path: /etc/nginx/nginx.conf
    line: 'daemon off;'
